language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t piyushsawaria1/docker-travis-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true piyushsawaria1/docker-travis-aws npm run test
